apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
  labels:
    app: spring-boot-k8s-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s-deployment
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-k8s-deployment
        tier: backend
    spec:
      containers:
      - name: spring-boot-k8s-pod
        image: stupidlylogical/spring-boot-k8s:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: default

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-service
  labels:
    app: spring-boot-k8s-service
spec:
  selector:
    app: spring-boot-k8s-deployment
    tier: backend
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort